SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY >=10000 AND SALARY <=12000;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 10000;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 135 OR EMPLOYEE_ID = 176 OR EMPLOYEE_ID = 154 OR EMPLOYEE_ID = 129;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = (135,176,154,129);

SELECT CITY
FROM LOCATIONS
WHERE COUNTRY_ID IN('IT','US','UK');

SELECT COUNT (*) FROM EMPLOYEES
WHERE JOB_ID IN('IT_PROG','SA_REP');

SELECT COUNT (*) FROM EMPLOYEES
WHERE SALARY > 8000;

SELECT COUNT(DISTINCT FIRST_NAME) FROM EMPLOYEES ;

SELECT * FROM EMPLOYEES
ORDER BY SALARY DESC ;

SELECT * FROM EMPLOYEES
ORDER BY FIRST_NAME;

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'C%';

SELECT JOB_ID FROM JOBS
WHERE JOB_ID LIKE 'C%';

SELECT JOB_TITLE FROM JOBS
WHERE JOBS.JOB_TITLE LIKE 'S%';

SELECT * FROM JOBS
WHERE JOBS.JOB_TITLE LIKE '%Manager';


SELECT HIRE_DATE,FIRST_NAME FROM EMPLOYEES
WHERE HIRE_DATE LIKE '%2006';

SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A____';

SELECT LAST_NAME FROM EMPLOYEES
WHERE LAST_NAME LIKE '_____a';

SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES
WHERE JOB_ID LIKE '%CLERK%';

SELECT EMAIL FROM EMPLOYEES
WHERE EMAIL LIKE '___E__';

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
WHERE LAST_NAME LIKE '_____';

SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE LIKE '%2005%';






SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%C%';




SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE 'C________';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '__z__';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_u%';

SELECT MIN(SALARY) FROM EMPLOYEES;

SELECT MAX(SALARY) FROM EMPLOYEES;

SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT ROUND(AVG(SALARY),2) FROM EMPLOYEES;

SELECT SUM(SALARY) FROM EMPLOYEES;

SELECT AVG(SALARY) FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

SELECT MAX(SALARY) FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

SELECT MIN(SALARY) FROM EMPLOYEES
WHERE JOB_ID = 'SA_REP';

SELECT SUM(SALARY) FROM EMPLOYEES
WHERE JOB_ID = 'ST_MAN';

SELECT AVG(SALARY) FROM EMPLOYEES
WHERE JOB_ID = 'SA_REP';



SELECT ROUND(AVG(SALARY)) FROM EMPLOYEES;

SELECT ROUND(AVG(SALARY),2) FROM EMPLOYEES;

SELECT ROUND(AVG(SALARY),3) FROM EMPLOYEES;

SELECT SALARY FROM EMPLOYEES;



--UNIQUE JOB ID

SELECT DISTINCT JOB_ID FROM EMPLOYEES;

SELECT JOB_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID ;

SELECT JOB_ID, AVG(SALARY), COUNT(*), SUM(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID ;

SELECT  * FROM LOCATIONS;

SELECT JOB_ID, MAX(HIRE_DATE) FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID ;

SELECT JOB_ID, AVG(SALARY)
FROM EMPLOYEES
WHERE SALARY>5000
GROUP BY JOB_ID ;


SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, MIN(SALARY), MAX(SALARY),  SUM (SALARY), AVG(SALARY),COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID ;

SELECT JOB_ID, MIN(SALARY), MAX(SALARY),  SUM (SALARY), AVG(SALARY), COUNT(*)
FROM EMPLOYEES
WHERE SALARY>20000
GROUP BY JOB_ID ;

SELECT JOB_ID, SUM (SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING SUM(SALARY) > 20000;

SELECT DEPARTMENT_ID, COUNT (*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 10;

SELECT DEPARTMENT_ID, COUNT (DEPARTMENT_ID)
FROM EMPLOYEES
WHERE DEPARTMENT_ID > 10
GROUP BY DEPARTMENT_ID;

SELECT JOB_ID, AVG(COMMISSION_PCT)
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING AVG(COMMISSION_PCT) > 0.20;

SELECT MANAGER_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING MAX(SALARY) > 10000
ORDER BY  MAX(SALARY);





