select * from JOBS;
 select * from JOB_HISTORY jobs

select JOB_TITLE, JOB_HISTORY.JOB_ID from JOBS
inner join JOB_HISTORY
on jobs.JOB_ID = JOB_HISTORY.JOB_ID;

select * from LOCATIONS;

select * from COUNTRIES;

select STREET_ADDRESS, POSTAL_CODE, CITY, COUNTRY_NAME from LOCATIONS
inner join COUNTRIES
on LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID;


select FIRST_NAME, DEPARTMENT_NAME from EMPLOYEES
inner join DEPARTMENTS on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

select j.JOB_ID, e.MANAGER_ID from JOBS j
inner join EMPLOYEES e on j.JOB_ID = e.JOB_ID;

select DEPARTMENT_NAME, FIRST_NAME, LAST_NAME  from EMPLOYEES inner join DEPARTMENTS
on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

select DEPARTMENT_NAME,STATE_PROVINCE from DEPARTMENTS left outer join LOCATIONS on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;

select FIRST_NAME, START_DATE  from EMPLOYEES left join JOB_HISTORY JH on EMPLOYEES.EMPLOYEE_ID = JH.EMPLOYEE_ID;

select FIRST_NAME, START_DATE from JOB_HISTORY left join EMPLOYEES on JOB_HISTORY.EMPLOYEE_ID = EMPLOYEES.EMPLOYEE_ID;

select STREET_ADDRESS, POSTAL_CODE, CITY from LOCATIONS;

select COUNTRY_NAME, REGION_NAME
from COUNTRIES inner join REGIONS on COUNTRIES.REGION_ID = REGIONS.REGION_ID;

select COUNTRY_NAME, REGION_NAME
from COUNTRIES full outer join REGIONS on COUNTRIES.REGION_ID = REGIONS.REGION_ID;