--how to find employees information of who is making highest salary in the company ?

--get higest salary

SELECT max(SALARY) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY = 24000;

SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT max(SALARY) FROM EMPLOYEES);

SELECT max(SALARY) FROM EMPLOYEES
WHERE SALARY < 24000;

SELECT max(SALARY) FROM EMPLOYEES
WHERE SALARY < (SELECT max(SALARY) FROM EMPLOYEES);

SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT max(SALARY) FROM EMPLOYEES WHERE SALARY < (SELECT max(SALARY) FROM EMPLOYEES));

SELECT * FROM EMPLOYEES
WHERE SALARY = 17000;

SELECT * FROM EMPLOYEES
WHERE ROWNUM < 11
ORDER BY SALARY DESC;

select count (*) salary from EMPLOYEES;

select count (distinct salary) from EMPLOYEES;
select distinct salary from EMPLOYEES
    order by salary;

select FIRST_NAME, LAST_NAME, EMPLOYEE_ID from EMPLOYEES
order by FIRST_NAME;

select FIRST_NAME, LAST_NAME from EMPLOYEES
order by FIRST_NAME;

select JOB_ID, MIN_SALARY FROM JOBS
WHERE MIN_SALARY > 4000 AND MIN_SALARY < 9000; --NOT INCLUDED

select JOB_ID, MIN_SALARY FROM JOBS
WHERE MIN_SALARY BETWEEN 4000 AND 9000; --INCLUDED


SELECT CITY, COUNTRY_ID FROM LOCATIONS
    WHERE COUNTRY_ID IN ('IT','IN');

SELECT CITY, COUNTRY_ID FROM LOCATIONS
WHERE COUNTRY_ID = 'IT' OR COUNTRY_ID ='IN';

SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES
    ORDER BY  HIRE_DATE;

SELECT FIRST_NAME FROM EMPLOYEES
ORDER BY  HIRE_DATE;


SELECT LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES
ORDER BY  COMMISSION_PCT;


SELECT FIRST_NAME, SALARY FROM EMPLOYEES
ORDER BY FIRST_NAME ASC, SALARY DESC;

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
ORDER BY FIRST_NAME ASC, LAST_NAME DESC;

SELECT FIRST_NAME, JOB_ID, SALARY FROM EMPLOYEES
ORDER BY JOB_ID ASC, SALARY DESC ;


--order all employees based on salary high to low then display only first 10 result
select *
from (select * from employees order by salary desc)
where rownum < 11;

SELECT FIRST_NAME AS "GIVEN NAME", LAST_NAME AS "SURNAME" FROM EMPLOYEES;


SELECT FIRST_NAME||' '||LAST_NAME AS "FULL_NAME" FROM EMPLOYEES;

SELECT EMPLOYEES.EMAIL||''||'@gmail.com' AS "EMAİL ADDRESS" FROM EMPLOYEES;
SELECT LOWER (EMAIL||''||'@gmail.com') AS "EMAİL ADDRESS" FROM EMPLOYEES;
SELECT UPPER (EMAIL||''||'@gmail.com') AS "EMAİL ADDRESS" FROM EMPLOYEES;

SELECT FIRST_NAME, LENGTH(FIRST_NAME) AS "LENGHT_NAME"
FROM EMPLOYEES
ORDER BY "LENGHT_NAME" DESC;


--VİEW
CREATE VIEW EMAILLIST AS SELECT SUBSTR(FIRST_NAME,0,1)||'.'||SUBSTR(LAST_NAME,0,1) AS "INITIALS",
FIRST_NAME||' '||LAST_NAME AS "FULL_NAME", LOWER (EMAIL||''||'@gmail.com') AS "EMAİL ADDRESS" FROM EMPLOYEES;

SELECT SUBSTR(FIRST_NAME,0,4) FROM
SELECT "FULL_NAME" FROM EMAILLIST;

SELECT JOB_TITLE, LENGTH(JOB_TITLE) FROM JOBS;

SELECT UPPER(CITY), LOWER(STREET_ADDRESS) FROM LOCATIONS;

SELECT EMPLOYEE_ID||SUBSTR(FIRST_NAME,0,2)||SUBSTR(JOB_ID,0,3)||DEPARTMENT_ID AS "PERSONEL ID" FROM EMPLOYEES;




--TO REMOVE VIEW

DROP VIEW EMAILLIST;

--14TH HIGHEST SALARY

select MIN(SALARY) FROM (select distinct SALARY from employees order by salary desc)
where rownum < 15;

--INFO OF MAKING 14TH HIGHEST SALARY
SELECT * FROM EMPLOYEES
WHERE SALARY = 10500;

SELECT * FROM EMPLOYEES
WHERE SALARY = (select MIN(SALARY)
                from (select distinct SALARY from employees order by salary desc)
                where rownum < 15);

select distinct SALARY from employees order by salary desc;

select MIN(SALARY) from (select distinct SALARY from employees order by salary desc)
where rownum < 15;







SELECT MAX(SALARY) FROM EMPLOYEES;

SELECT FIRST_NAME FROM EMPLOYEES
WHERE SALARY=24000;

SELECT FIRST_NAME FROM EMPLOYEES
WHERE SALARY= (SELECT MAX(SALARY) FROM EMPLOYEES);

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE ROWNUM < 11;

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT FIRST_NAME, SALARY FROM (SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM <11;

SELECT COUNT (DEPARTMENT_ID) FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80;

SELECT DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(DEPARTMENT_ID) > (SELECT COUNT (DEPARTMENT_ID) FROM EMPLOYEES
                               WHERE DEPARTMENT_ID = 80);

SELECT MIN(HIRE_DATE) FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE < (SELECT MIN(HIRE_DATE) FROM EMPLOYEES
                   WHERE JOB_ID = 'IT_PROG');
